name: Build and Publish Docker

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '5 5 1 * *'

jobs:
  update_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
      - name : update lists
        shell: bash
        run : |
          bash update-known-public-dns.sh
      - name: push updated lists
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: update-lists