name: Build and Publish Docker

on:
  push:
    branches:
      - master

jobs:
  update_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name : pull and update lists
        shell: bash
        run : |
          git clone https://github.com/takuya/public_dns_list.git
          bash update-known-public-dns.sh
      - name: Update API docs
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: update-lists